sudo: false

language: java

jdk:
  - oraclejdk8

before_cache:
- git status

  
before_install:
 - chmod +x ./dev/gradlew
 - cd dev


install: ./gradlew cnf:initialize --no-daemon


script: ./gradlew build --no-daemon


