sudo: false

language: java

jdk:
  - oraclejdk8

env:
  - TERM=dumb

  
before_install:
 - chmod +x ./dev/gradlew
 - cd dev


install: ./gradlew cnf:initialize --no-daemon


script: ./gradlew build --no-daemon --continue


