/*
 * 
 * 
 * ============================================================================
 * IBM Confidential OCO Source Materials
 * 
 * Copyright IBM Corp. 2012
 * 
 * The source code for this program is not published or otherwise divested
 * of its trade secrets, irrespective of what has been deposited with the
 * U.S. Copyright Office.
 * ============================================================================
 * 
 *
 * Change activity:
 *
 * Reason           Date   Origin   Description
 * ---------------  ------ -------- -------------------------------------------------
 * TBD              260303 astley   First version
 * 166318.3         090603 nyoung   Replace Gryphon utilities with JDK Equivalents
 * 166318.5         190603 nyoung   Integrate MatchSpace with MP.
 * 166318.9         160603 nyoung   Restructure mspace interfaces
 * 166318.10        230903 nyoung   Move to matchspace.impl component
 * 180784           231003 nyoung   Disable GeneralSetPredicate support
 * 166318.12        121103 nyoung   Remove support for BooleanValue and NumericValue
 * 166318.13        201103 auerbach Remove obsolete/unused list support
 * 166318.14        011203 auerbach Optimized LIKE processing and generalized TOPIC
 * ===========================================================================
 */
/* Generated By:JavaCC: Do not edit this line. MatchParserImplConstants.java */
package com.ibm.ws.sib.matchspace.selector.impl;

public interface MatchParserImplConstants {

  int EOF = 0;
  int IS = 19;
  int IN = 20;
  int BETWEEN = 21;
  int LIKE = 22;
  int ESCAPE = 23;
  int OR = 24;
  int AND = 25;
  int NOT = 26;
  int NULL = 27;
  int TRUE = 28;
  int FALSE = 29;
  int IDENTIFIER = 30;
  int QUOTED_IDENTIFIER = 31;
  int LETTER = 32;
  int DIGIT = 33;
  int FIELDSEP = 34;
  int INTEGER_LITERAL = 35;
  int FLOATING_POINT_LITERAL = 36;
  int EXPONENT = 37;
  int STRING_LITERAL = 38;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"IS\"",
    "\"IN\"",
    "\"BETWEEN\"",
    "\"LIKE\"",
    "\"ESCAPE\"",
    "\"OR\"",
    "\"AND\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<FIELDSEP>",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
  };

}
