
all:
	@echo "Please use gmake instead of make.  GNU make supports -j for parallel builds."
	gmake all

%:
	@echo "Please use gmake instead of make.  GNU make supports -j for parallel builds."
	gmake $@

