//* ===========================================================================
//*
//* IBM SDK, Java(tm) 2 Technology Edition, v5.0
//* (C) Copyright IBM Corp. 2005, 2006
//*
//* The source code for this program is not published or otherwise divested of
//* its trade secrets, irrespective of what has been deposited with the U.S.
//* Copyright office.
//*
//* ===========================================================================
//
//@(#) 1.5 SERV1/ws/code/channelfw/src/com/ibm/websphere/channel/framework/ChannelFactoryData.java, WAS.channelfw, WASX.SERV1 5/26/04 08:38:14 [8/28/04 13:40:12]

package com.ibm.websphere.channelfw;

import java.io.Serializable;
import java.util.Map;

/**
 * This class represents the data associated with a channel factory.
 * <p>
 * Each Channel has a ChannelFactory associated with it. This ChannelFactory contains
 * important information for ensuring the coherency of the Chain (protocol stack) as well
 * as storing configuration data for resources that may be scoped to a ChannelFactory
 * level.
 * 
 * @ibm-api
 */
public interface ChannelFactoryData extends Serializable {
    /**
     * Returns the interface into this channel. Return the interface class that this channel
     * presents to adjacent channels on its application side.
     * 
     * @return Class<?>
     */
    Class<?> getApplicationInterface();

    /**
     * Return the list of device interface classes supported. These
     * interfaces represent the type of objects that can be passed from
     * an adjacent channel to this channel on its device side.
     * 
     * @return Class<?>[]
     */
    Class<?>[] getDeviceInterface();

    /**
     * Get the common properties that are to be shared by all channel instances
     * generated by this factory.
     * 
     * @return Map<Object,Object> common properties
     */
    Map<Object, Object> getProperties();

    /**
     * Returns the class of the ChannelFactory associated with this data
     * 
     * @return Class<?>
     */
    Class<?> getFactory();

}
