// /I/ /W/ /G/ /U/   <-- CMVC Keywords, replace / with %
// %I% %W% %G% %U%
//
// IBM Confidential OCO Source Material
// 5724-J08, 5724-I63, 5724-H88, 5724-H89, 5655-N02, 5733-W70 (C) COPYRIGHT International Business Machines Corp. 2007, 2009
//
// The source code for this program is not published or otherwise divested
// of its trade secrets, irrespective of what has been deposited with the
// U.S. Copyright Office.
//
// Module  :  package-info.java
//
// Change Activity:
//
// Reason    Version   Date     Userid    Change Description
// --------- --------- -------- --------- -----------------------------------------
//           EJB3      20071020 leealber : Initial Release
// d406994   EJB3      20071122 leealber : CI:change package to com.ibm.ws.jpa.pxml10
// d446928   EJB3      20071122 leealber : Regenerate for JAXB2.0 20070612 level
// F1879-16302
//           WAS80     20091112 tkb      : reverted back to 1.0 schema level
// --------- --------- -------- --------- -----------------------------------------

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.11.17 at 04:47:21 PM CST
//
/**
 * @version 1.0.16
 */
@org.osgi.annotation.versioning.Version("1.0.16")
@javax.xml.bind.annotation.XmlSchema(namespace = "http://java.sun.com/xml/ns/persistence", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ibm.ws.jpa.pxml10;
